### ISSUE TITLE
Home Page Issue 

### ISSUE THREAD

**Issue by mrinmoyf2** [gdgsiliguri/devFest2019#1]
When I open the official website of GDGSiliguri on the mobile phone, the Home page doesn't fill up the width except for navbar and google map. I think it's for that Google Map size.

![WhatsApp Image 2019-08-11 at 2 23 39 PM](https://user-images.githubusercontent.com/33196122/62831944-777d2900-bc44-11e9-9b79-6857113e118a.jpeg)

**Comment by tanmoyio** [comment]
I have adjusted the grids, hope this will work on all devices out there
