### ISSUE TITLE
Hyperlink issues

### ISSUE THREAD

**Issue by mrinmoyf2** [gdgsiliguri/devFest2019#18]
Add target Attribute in Aniket Ghosh's links (Team Page).

**Comment by tanmoyio** [comment]
can you provide us detailed info, I am not getting any issues

**Comment by mrinmoyf2** [comment]
I think this is my mistake.😅Actually when i gone through the team page , it seems that there is an issue .  But now i check it I didn't see any issues .  so maybe this is my mistake .
